-- Written by Rabia Alhaffar in 19/August/2020
-- TARGET! assets manager!

function load_assets()
  -- Load sounds, Then images!
  explosion_sound = rl.LoadSound("resources/audio/explosion1.wav")
  powerup_sound = rl.LoadSound("resources/audio/powerup1.wav")
  --heal_sound = rl.LoadSound("resources/audio/powerup2.wav")
  select_sound = rl.LoadSound("resources/audio/select3.wav")
  shoot_sound = rl.LoadSound("resources/audio/shoot3.wav")
  death_sound = rl.LoadSound("resources/audio/over1.wav")
  gameover_sound = rl.LoadSound("resources/audio/over2.wav")
  --portal_sound = rl.LoadSound("resources/audio/coin1.wav")
  hit1_sound = rl.LoadSound("resources/audio/hurt1.wav")
  hit2_sound = rl.LoadSound("resources/audio/hurt2.wav")
  hit3_sound = rl.LoadSound("resources/audio/hurt3.wav")
  hit4_sound = rl.LoadSound("resources/audio/hurt4.wav")
  
  raylua_logo = rl.LoadTexture("resources/images/raylua.png")
  ship_image = rl.LoadTexture("resources/images/flash.png")
  --heal_image = rl.LoadTexture("resources/images/heal.png")
  --powerup_image = rl.LoadTexture("resources/images/power.png")
  --portal_image = rl.LoadTexture("resources/images/portal.png")
  enemy1_image = rl.LoadTexture("resources/images/enemy1.png")
  --enemy2_image = rl.LoadTexture("resources/images/ship1.png")
  enemy3_image = rl.LoadTexture("resources/images/ship2.png")
  enemy4_image = rl.LoadTexture("resources/images/lasership3.png")
  enemy5_image = rl.LoadTexture("resources/images/lasership2.png")
  --enemy6_image = rl.LoadTexture("resources/images/lasership1.png")
  enemy7_image = rl.LoadTexture("resources/images/ninship.png")
  --apple_image = rl.LoadTexture("resources/images/apple.png")
  shot_image = rl.LoadTexture("resources/images/shot.png")
  star_image = rl.LoadTexture("resources/images/star.png")
  explosion_image = rl.LoadTexture("resources/images/explosion.png")
end

function unload_assets()
  -- Unload sounds, Then unload images!
  rl.UnloadSound(explosion_sound)
  rl.UnloadSound(powerup_sound)
  --rl.UnloadSound(heal_sound)
  rl.UnloadSound(select_sound)
  rl.UnloadSound(shoot_sound)
  rl.UnloadSound(gameover_sound)
  --rl.UnloadSound(portal_sound)
  rl.UnloadSound(hit1_sound)
  rl.UnloadSound(hit2_sound)
  rl.UnloadSound(hit3_sound)
  rl.UnloadSound(hit4_sound)
  
  rl.UnloadTexture(raylua_logo)
  rl.UnloadTexture(ship_image)
  --rl.UnloadTexture(heal_image)
  --rl.UnloadTexture(powerup_image)
  --rl.UnloadTexture(portal_image)
  rl.UnloadTexture(enemy1_image)
  --rl.UnloadTexture(enemy2_image)
  rl.UnloadTexture(enemy3_image)
  rl.UnloadTexture(enemy4_image)
  rl.UnloadTexture(enemy5_image)
  --rl.UnloadTexture(enemy6_image)
  rl.UnloadTexture(enemy7_image)
  --rl.UnloadTexture(apple_image)
  rl.UnloadTexture(shot_image)
  rl.UnloadTexture(star_image)
  rl.UnloadTexture(explosion_image)
end